config/routes.rb
Rails.application.routes.draw do
  get 'starships/index'
  get 'starships/show'
  root to: 'characters#index'

  get 'search/index'

  get 'about', to: 'about#index'

  get 'characters', to: 'characters#index'
  resources 'characters', only: %i[index show]

  get 'homeworlds', to: 'homeworlds#index'
  resources 'homeworlds', only: %i[index show]

  get 'speciess', to: 'species#index'
  resources 'species', only: %i[index show]

  get 'starships', to: 'starships#index'
  resources 'starships', only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :vehicles
  belongs_to :homeworld
  belongs_to :species

  validates :name, :birth_year, :homeworld, presence: true
end

app/models/homeworld.rb
class Homeworld < ApplicationRecord
  has_many :characters
end

app/models/species.rb
class Species < ApplicationRecord
  has_many :characters
end

app/models/starship.rb
class Starship < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.includes(:species, :homeworld).all.paginate(:page => params[:page], :per_page => 12)
  end

  def show
    @character = Character.find(params[:id])
  end
end

app/controllers/homeworlds_controller.rb
class HomeworldsController < ApplicationController
  def index
    @homeworlds = Homeworld.all.paginate(:page => params[:page], :per_page => 12)
  end

  def show
    @homeworlds = Homeworld.find(params[:id])
    @people = Character.where(homeworld_id: @homeworlds.id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search = params["search"]
    if @search.present?
      @name = @search["name"]
      @characters = Character.where("name LIKE ?", "%#{@name}%")
      @homeworlds = Homeworld.where("name LIKE ?", "%#{@name}%")
      @species = Species.where("name LIKE ?", "%#{@name}%")
      @starships = Starship.where("name LIKE ?", "%#{@name}%")
    end
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all.paginate(:page => params[:page], :per_page => 12)
  end

  def show
    @species = Species.find(params[:id])
    @people = Character.where(species_id: @species.id)
  end
end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController
  def index
    @starships = Starship.all.paginate(:page => params[:page], :per_page => 12)
  end

  def show
    @starships = Starship.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/homeworlds_helper.rb
module HomeworldsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/about/index.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div class="card text-white bg-dark">
      <h1 class="card-header">About Us </h1>
      <div class="card-body">
        <h4 class="card-text row justify-content-center">Welcome to my About Page </h4>
        <p class="card-text"><strong>Data Souce used:</strong> <a href="https://swapi.dev/">https://swapi.dev/</a> </p>
        <p class="card-text"><strong>Faker Data Souce used:</strong> <a href="https://github.com/faker-ruby/">https://github.com/faker-ruby/</a> </p>
        <p class="card-text"><strong>Entity Relationship Diagram:</strong> </p>
        <img src="/ERD.jpg" alt="Entity Relationship Diagram" class="justify-content-center">
      </div>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<h1 class="mb-5 row mr-0 ml-0 justify-content-center">Characters</h1>
<div class="row mr-0 ml-0 justify-content-center">
  <div class="col-8">
    <table id="fullTable" class="table table-striped table-dark table-hover">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Species</th>
        <th scope="col">Homeworld</th>
      </tr>
      <% @characters.each do |character| %>
      <tr>
        <th><%= link_to character.id, character_path(character), class: "nav-link text-white" %></th>
        <th><%= link_to character.name, character_path(character), class: "nav-link text-white" %></th>
        <th><%= link_to character.species.name, species_path(character.species), class: "nav-link text-white" %></th>
        <th><%= link_to character.homeworld.name.capitalize(), homeworld_path(character.homeworld), class: "nav-link text-white" %></th>
      </tr>
      <% end %>
    </table>
    <div class="flickr_pagination">
      <%= will_paginate @characters, :container => false %>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div class="card text-white bg-dark">
      <h1 class="card-header">Name: <%= @character.name %></h1>
      <div class="card-body">
        <p class="card-text"><strong>Species:</strong> <%= link_to @character.species.name, species_path(@character.species.id), class: "d-inline" %></p>
        <p class="card-text"><strong>Gender:</strong> <%= @character.gender.capitalize() %></p>
        <p class="card-text"><strong>Homeworld:</strong> <%= link_to @character.homeworld.name, homeworld_path(@character.homeworld.id), class: "d-inline" %></p>
        <p class="card-text"><strong>Birth Year:</strong> <%= @character.birth_year.capitalize() %></p>
        <p class="card-text"><strong>Mass:</strong> <%= @character.mass %> Kg</p>
        <p class="card-text"><strong>Hair Color:</strong> <%= @character.hair_color.capitalize() %></p>
        <p class="card-text"><strong>Skin Color:</strong> <%= @character.skin_color.capitalize() %></p>
        <p class="card-text"><strong>Eye Color:</strong> <%= @character.eye_color.capitalize() %></p>
        <p class="card-text"><strong>Height:</strong> <%= @character.height %> Cm</p>
      </div>
    </div>
  </div>
</div>

app/views/homeworlds/index.html.erb
<h1 class="mb-5 row mr-0 ml-0 justify-content-center">Homeworlds</h1>
<div class="row mr-0 ml-0 justify-content-center">
  <div class="col-8">
    <table id="fullTable" class="table table-striped table-dark table-hover">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Rotation Period</th>
        <th scope="col">Climate</th>
      </tr>
      <% @homeworlds.each do |world| %>
      <tr>
        <th scope="row mr-0 ml-0"><%= link_to world.id, homeworld_path(world), class: "nav-link text-white" %></th>
        <th><%= link_to world.name, homeworld_path(world), class: "nav-link text-white" %></th>
        <th><%= link_to world.rotation_period, homeworld_path(world), class: "nav-link text-white" %></th>
        <th><%= link_to world.climate.capitalize(), homeworld_path(world), class: "nav-link text-white" %></th>
      </tr>
      <% end %>
    </table>
    <div class="flickr_pagination">
      <%= will_paginate @characters, :container => false %>
    </div>
  </div>
</div>

app/views/homeworlds/show.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div class="card text-white bg-dark">
      <h1 class="card-header">Name: <%= @homeworlds.name %></h1>
      <div class="card-body">
        <p class="card-text"><strong>Rotation Period:</strong> <%= @homeworlds.rotation_period %></p>
        <p class="card-text"><strong>Climate:</strong> <%= @homeworlds.climate.capitalize() %></p>
        <p class="card-text"><strong>Diameter:</strong> <%= @homeworlds.diameter %> Km</p>
        <p class="card-text"><strong>Gravity:</strong> <%= @homeworlds.gravity %></p>
        <p class="card-text"><strong>Terrain:</strong> <%= @homeworlds.terrain.capitalize() %></p>
        <p class="card-text"><strong>Surface Water:</strong> <%= (@homeworlds.surface_water == '1') ? 'True' : 'False' %></p>
        <p class="card-text"><strong>Population:</strong> <%= (@homeworlds.population == 0) ? 'Unknown' : @homeworlds.population %></p>
        <p class="card-text"><strong>People:</strong></p>
        <ul>
        <% @people.each do |person| %>
          <li class="card-text"><%= link_to person['name'], character_url(person.id), class: "" %> </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Star Wars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand">Star Wars Wiki</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
            <%= link_to 'Characters', root_path, class: "nav-link" %>  <span class="sr-only">(current)</span>
          </li>
          <li class="nav-item <%= 'active' if current_page?(homeworlds_path) %>">
            <%= link_to 'Homeworlds', homeworlds_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(speciess_path) %>">
            <%= link_to 'Species', speciess_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(starships_path) %>">
            <%= link_to 'Starships', starships_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(about_path) %>">
            <%= link_to 'About', about_path, class: "nav-link" %>
          </li>
        </ul>
        <%= simple_form_for :search, url: search_index_path, class: "form-inline my-2 my-lg-0", method: "GET", html: { class: 'form-inline' } do |f| %>
          <%= f.input :name, input_html: {value: "", class: "mr-2 p-1"}, label: false %>
          <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      </div>
    </nav>
    <div class="row mr-0 ml-0 justify-content-center">
      <div class="col-8 mt-5">
      </div>
  </div>
  <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<div class="row mr-0 ml-0 justify-content-center">
  <div class="col-6">
    <h1 class="mb-5 row mr-0 ml-0 justify-content-center">Search Results</h1>

    <div class="card text-white bg-dark">
      <h3 class="card-header">Characters</h3>
      <div class="card-body">
        <% @characters.each do |character| %>
          <p class="card-text"><%= link_to character.name, character_path(character) %></p>
        <% end %>
      </div>
    </div>

    <div class="card text-white bg-dark mt-2">
      <h3 class="card-header">Homeworlds</h3>
      <div class="card-body">
        <% @homeworlds.each do |world| %>
          <p class="card-text"><%= link_to world.name, homeworld_path(world) %></p>
        <% end %>
      </div>
    </div>

    <div class="card text-white bg-dark mt-2">
      <h3 class="card-header">Species</h3>
      <div class="card-body">
        <% @species.each do |spec| %>
          <p class="card-text"><%= link_to spec.name, species_url(spec) %></p>
        <% end %>
      </div>
    </div>

    <div class="card text-white bg-dark mt-2 mb-4">
      <h3 class="card-header">Starships</h3>
      <div class="card-body">
        <% @starships.each do |starship| %>
          <p class="card-text"><%= link_to starship.name, starship_url(starship) %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/species/index.html.erb
<h1 class="mb-5 row mr-0 ml-0 justify-content-center">Species</h1>
<div class="row mr-0 ml-0 justify-content-center">
  <div class="col-8">
    <table id="fullTable" class="table table-striped table-dark table-hover">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Classification</th>
        <th scope="col">Designation</th>
        <th scope="col">Average Height</th>
      </tr>
      <% @species.each do |spec| %>
      <tr>
        <th><%= link_to spec.id, species_url(spec), class: "nav-link text-white" %></th>
        <th><%= link_to spec.name, species_url(spec), class: "nav-link text-white" %></th>
        <th><%= link_to spec.classification.capitalize(), species_url(spec), class: "nav-link text-white" %></th>
        <th><%= link_to spec.designation.capitalize(), species_url(spec), class: "nav-link text-white" %></th>
        <th><%= link_to spec.average_height, species_url(spec), class: "nav-link text-white"  %></th>
      </tr>
      <% end %>
    </table>
    <div class="flickr_pagination">
      <%= will_paginate @species, :container => false %>
    </div>
  </div>
</div>

app/views/species/show.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div class="card text-white bg-dark">
      <h1 class="card-header">Name: <%= @species.name %></h1>
      <div class="card-body">
        <p class="card-text"><strong>Classification:</strong> <%= @species.classification.capitalize() %></p>
        <p class="card-text"><strong>Designation:</strong> <%= @species.designation.capitalize() %></p>
        <p class="card-text"><strong>Average Height:</strong> <%= @species.average_height %> Cm</p>
        <p class="card-text"><strong>Language:</strong> <%= @species.language.capitalize() %></p>
        <p class="card-text"><strong>Average Lifespan:</strong> <%= @species.average_lifespan %> Years</p>
        <p class="card-text"><strong>People:</strong></p>
        <ul>
        <% @people.each do |person| %>
          <li class="card-text"><%= link_to person['name'], character_url(person.id), class: "" %> </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/starships/index.html.erb
<h1 class="mb-5 row mr-0 ml-0 justify-content-center">Species</h1>
<div class="row mr-0 ml-0 justify-content-center">
  <div class="col-8">
    <table id="fullTable" class="table table-striped table-dark table-hover">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Model</th>
        <th scope="col">Hyperdrive Rating</th>
      </tr>
      <% @starships.each do |starship| %>
      <tr>
        <th><%= link_to starship.id, starship_url(starship), class: "nav-link text-white" %></th>
        <th><%= link_to starship.name, starship_url(starship), class: "nav-link text-white" %></th>
        <th><%= link_to starship.model, starship_url(starship), class: "nav-link text-white" %></th>
        <th><%= link_to starship.hyperdrive_rating, starship_url(starship), class: "nav-link text-white" %></th>
      </tr>
      <% end %>
    </table>
    <div class="flickr_pagination">
      <%= will_paginate @starships, :container => false %>
    </div>
  </div>
</div>

app/views/starships/show.html.erb
<div class="row justify-content-center">
  <div class="col-8">
    <div class="card text-white bg-dark">
      <h1 class="card-header">Name: <%= @starships.name %></h1>
      <div class="card-body">
        <p class="card-text"><strong>Cargo Capacity:</strong> <%= @starships.cargo_capacity %></p>
        <p class="card-text"><strong>Consumables:</strong> <%= @starships.consumables %></p>
        <p class="card-text"><strong>Crew:</strong> <%= @starships.crew %></p>
        <p class="card-text"><strong>Hyperdrive Rating:</strong> <%= @starships.hyperdrive_rating %></p>
        <p class="card-text"><strong>Manufacturer:</strong> <%= @starships.manufacturer.capitalize() %></p>
        <p class="card-text"><strong>Model:</strong> <%= @starships.model.capitalize() %> </p>
      </div>
    </div>
  </div>
</div>